#!/bin/bash
# =============================================================================
# Extract Current Schema from Production
# =============================================================================
# Downloads the current production schema and saves it locally
# This is useful for:
#   - Initial schema.sql creation
#   - Updating schema.sql to match production
#   - Troubleshooting schema drift
# =============================================================================

set -e

# Configuration
SERVER="${SERVER:-138.68.245.159}"
SSH_USER="${SSH_USER:-root}"
DB_NAME="${DB_NAME:-trad}"
DB_USER="${DB_USER:-postgres}"
OUTPUT_FILE="${OUTPUT_FILE:-sql/schema_production_dump.sql}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Extracting production schema...${NC}"
echo "Server: $SERVER"
echo "Database: $DB_NAME"
echo "Output: $OUTPUT_FILE"
echo ""

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Extract schema
ssh $SSH_USER@$SERVER "sudo -u $DB_USER pg_dump -d $DB_NAME --schema-only --no-owner --no-acl" > "$OUTPUT_FILE"

# Add header
cat > /tmp/schema_header.sql << 'EOF'
-- =============================================================================
-- TradePulse IQ - Production Schema Dump
-- =============================================================================
-- This schema was extracted from production database
-- Generated: $(date)
-- Server: $SERVER
-- Database: $DB_NAME
-- =============================================================================
-- DO NOT EDIT THIS FILE MANUALLY
-- This is a reference dump. Edit sql/schema.sql instead.
-- =============================================================================

EOF

# Combine header and schema
cat /tmp/schema_header.sql "$OUTPUT_FILE" > /tmp/schema_combined.sql
mv /tmp/schema_combined.sql "$OUTPUT_FILE"

# Show statistics
TABLE_COUNT=$(grep -c "^CREATE TABLE" "$OUTPUT_FILE" || echo 0)
INDEX_COUNT=$(grep -c "^CREATE INDEX" "$OUTPUT_FILE" || echo 0)
VIEW_COUNT=$(grep -c "^CREATE VIEW" "$OUTPUT_FILE" || echo 0)

echo -e "${GREEN}✓ Schema extracted successfully${NC}"
echo ""
echo "Statistics:"
echo "  Tables:  $TABLE_COUNT"
echo "  Indexes: $INDEX_COUNT"
echo "  Views:   $VIEW_COUNT"
echo ""
echo "Saved to: $OUTPUT_FILE"
