#!/usr/bin/env bash
# TradePulse IQ Server Quick Access Script
# Usage: ./server_info.sh

echo "🌐 TradePulse IQ Server Information"
echo "=================================="
echo ""
echo "📍 Server Details:"
echo "   IP Address: 138.68.245.159"
echo "   SSH Access: ssh root@138.68.245.159"
echo "   Deploy Path: /srv/trad"
echo ""
echo "🚀 Deployment Command:"
echo "   SERVER=138.68.245.159 SSH_USER=root DEST=/srv/trad ./ops/scripts/deploy_to_server.sh"
echo ""
echo "🔍 Health Checks:"
echo "   API Health: curl http://138.68.245.159:8000/health"
echo "   API Docs:   http://138.68.245.159:8000/docs"
echo "   Local Test: ./ops/scripts/health_check.sh"
echo ""
echo "📊 Services:"
echo "   Trading Bot: sudo systemctl status trad.service"
echo "   Dashboard:   sudo systemctl status dashboard.service"
echo ""
echo "📝 Logs:"
echo "   Trading:   sudo journalctl -u trad.service -f"
echo "   Dashboard: sudo journalctl -u dashboard.service -f"
echo ""
echo "🗄️ Database:"
echo "   Host: localhost, Port: 5432, DB: trad"
echo "   User: traduser, Password: TRAD123!"
echo ""
echo "📚 Full Documentation: ./DEPLOYMENT_GUIDE.md"