-- =============================================================================
-- TradePulse IQ - Production Schema Dump
-- =============================================================================
-- This schema was extracted from production database
-- Generated: $(date)
-- Server: $SERVER
-- Database: $DB_NAME
-- =============================================================================
-- DO NOT EDIT THIS FILE MANUALLY
-- This is a reference dump. Edit sql/schema.sql instead.
-- =============================================================================

--
-- PostgreSQL database dump
--

\restrict C6tHVQKeckSFsJ7JVQA8AIYSlw4roa48ZGzaY5JRCgtUCJQBrWGxx5psObkHEL7

-- Dumped from database version 17.6 (Ubuntu 17.6-0ubuntu0.25.04.1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-0ubuntu0.25.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_trained_configurations_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_trained_configurations_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_training_progress_timestamp(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_training_progress_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: active_trades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.active_trades (
    id integer NOT NULL,
    user_id integer,
    symbol character varying(255) NOT NULL,
    direction character varying(10) NOT NULL,
    entry_price numeric(18,8) NOT NULL,
    quantity numeric(18,8) NOT NULL,
    current_price numeric(18,8),
    unrealized_pnl numeric(18,8),
    unrealized_pnl_percent numeric(8,4),
    stop_loss numeric(18,8),
    take_profit numeric(18,8),
    strategy_name character varying(255),
    entry_timestamp timestamp with time zone NOT NULL,
    last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_paper_trade boolean DEFAULT false,
    CONSTRAINT active_trades_direction_check CHECK (((direction)::text = ANY ((ARRAY['BUY'::character varying, 'SELL'::character varying, 'LONG'::character varying, 'SHORT'::character varying])::text[])))
);


--
-- Name: TABLE active_trades; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.active_trades IS 'Currently open positions being monitored';


--
-- Name: active_trades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.active_trades_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: active_trades_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.active_trades_id_seq OWNED BY public.active_trades.id;


--
-- Name: backtest_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backtest_results (
    id integer NOT NULL,
    pattern_name character varying(255) NOT NULL,
    symbol character varying(50) NOT NULL,
    entry_time timestamp with time zone NOT NULL,
    entry_price numeric NOT NULL,
    exit_time timestamp with time zone,
    exit_price numeric,
    pnl_percentage numeric,
    trade_type character varying(10) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: backtest_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.backtest_results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: backtest_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.backtest_results_id_seq OWNED BY public.backtest_results.id;


--
-- Name: collection_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collection_runs (
    id bigint NOT NULL,
    run_type character varying(50) NOT NULL,
    exchange character varying(50) NOT NULL,
    symbols text[] NOT NULL,
    timeframes text[],
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone,
    status character varying(20) DEFAULT 'running'::character varying,
    records_collected integer DEFAULT 0,
    errors_count integer DEFAULT 0,
    error_details text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE collection_runs; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.collection_runs IS 'Metadata tracking for data collection runs';


--
-- Name: collection_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.collection_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: collection_runs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.collection_runs_id_seq OWNED BY public.collection_runs.id;


--
-- Name: current_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.current_embeddings (
    symbol character varying(20) NOT NULL,
    embedding_json text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    model_id character varying(50)
);


--
-- Name: equity_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equity_history (
    id integer NOT NULL,
    user_id integer,
    "timestamp" timestamp with time zone NOT NULL,
    equity numeric(18,8) NOT NULL,
    cash numeric(18,8) DEFAULT 0 NOT NULL,
    market_value numeric(18,8) DEFAULT 0 NOT NULL,
    total_pnl numeric(18,8) DEFAULT 0,
    daily_return numeric(8,6),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE equity_history; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.equity_history IS 'Historical equity values for performance charting';


--
-- Name: equity_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.equity_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: equity_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.equity_history_id_seq OWNED BY public.equity_history.id;


--
-- Name: market_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_data (
    id bigint NOT NULL,
    exchange character varying(50) NOT NULL,
    symbol character varying(20) NOT NULL,
    timeframe character varying(10) NOT NULL,
    "timestamp" bigint NOT NULL,
    open numeric(20,8) NOT NULL,
    high numeric(20,8) NOT NULL,
    low numeric(20,8) NOT NULL,
    close numeric(20,8) NOT NULL,
    volume numeric(20,8) NOT NULL,
    quote_volume numeric(20,8) DEFAULT NULL::numeric,
    trade_count integer,
    created_at timestamp with time zone DEFAULT now()
)
WITH (fillfactor='90');


--
-- Name: TABLE market_data; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.market_data IS 'Multi-timeframe OHLCV data for ML training';


--
-- Name: exchange_spreads; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.exchange_spreads AS
 SELECT symbol,
    timeframe,
    "timestamp",
    (max(close) - min(close)) AS price_spread,
    (((max(close) - min(close)) / avg(close)) * (100)::numeric) AS spread_pct,
    count(*) AS exchange_count
   FROM public.market_data
  WHERE ((timeframe)::text = '1h'::text)
  GROUP BY symbol, timeframe, "timestamp"
 HAVING (count(*) > 1)
  ORDER BY "timestamp" DESC, (((max(close) - min(close)) / avg(close)) * (100)::numeric) DESC;


--
-- Name: holdings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holdings (
    id integer NOT NULL,
    user_id integer,
    symbol character varying(255) NOT NULL,
    quantity numeric(18,8) DEFAULT 0 NOT NULL,
    avg_cost numeric(18,8) DEFAULT 0 NOT NULL,
    current_price numeric(18,8),
    market_value numeric(18,8),
    unrealized_pnl numeric(18,8),
    unrealized_pnl_percent numeric(8,4),
    last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE holdings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.holdings IS 'Current positions and holdings by user';


--
-- Name: holdings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.holdings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: holdings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.holdings_id_seq OWNED BY public.holdings.id;


--
-- Name: latest_prices; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.latest_prices AS
 SELECT symbol,
    exchange,
    timeframe,
    close AS price,
    volume,
    "timestamp",
    to_timestamp((("timestamp" / 1000))::double precision) AS price_time
   FROM public.market_data m1
  WHERE ("timestamp" = ( SELECT max(m2."timestamp") AS max
           FROM public.market_data m2
          WHERE (((m2.exchange)::text = (m1.exchange)::text) AND ((m2.symbol)::text = (m1.symbol)::text) AND ((m2.timeframe)::text = '1h'::text))))
  ORDER BY symbol, exchange;


--
-- Name: market_data_enhanced_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.market_data_enhanced_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: market_data_enhanced_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.market_data_enhanced_id_seq OWNED BY public.market_data.id;


--
-- Name: market_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_state (
    id integer NOT NULL,
    current_regime character varying(50) NOT NULL,
    conviction double precision NOT NULL,
    last_updated timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: market_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.market_state_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: market_state_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.market_state_id_seq OWNED BY public.market_state.id;


--
-- Name: order_book_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_book_snapshots (
    id bigint NOT NULL,
    exchange character varying(50) NOT NULL,
    symbol character varying(20) NOT NULL,
    "timestamp" bigint NOT NULL,
    bids jsonb NOT NULL,
    asks jsonb NOT NULL,
    best_bid numeric(20,8),
    best_ask numeric(20,8),
    spread numeric(20,8),
    spread_pct numeric(10,6),
    mid_price numeric(20,8),
    bid_depth numeric(20,8),
    ask_depth numeric(20,8),
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE order_book_snapshots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.order_book_snapshots IS 'Order book depth snapshots for liquidity analysis';


--
-- Name: order_book_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.order_book_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: order_book_snapshots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.order_book_snapshots_id_seq OWNED BY public.order_book_snapshots.id;


--
-- Name: strategy_exchange_performance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_exchange_performance (
    id integer NOT NULL,
    strategy_id integer,
    user_id integer,
    exchange character varying(255) NOT NULL,
    symbol character varying(255),
    total_trades integer DEFAULT 0,
    win_rate numeric(6,4),
    avg_profit numeric(18,8),
    avg_loss numeric(18,8),
    total_pnl numeric(18,8) DEFAULT 0,
    avg_slippage numeric(6,4),
    avg_fees numeric(6,4),
    avg_latency_ms integer,
    fill_rate numeric(6,4),
    status character varying(20) DEFAULT 'ACTIVE'::character varying,
    last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pattern_exchange_performance_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'PAPER_TRADING'::character varying, 'DISABLED'::character varying])::text[])))
);


--
-- Name: TABLE strategy_exchange_performance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.strategy_exchange_performance IS 'Exchange-specific pattern performance metrics';


--
-- Name: pattern_exchange_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pattern_exchange_performance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pattern_exchange_performance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pattern_exchange_performance_id_seq OWNED BY public.strategy_exchange_performance.id;


--
-- Name: strategy_parameters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_parameters (
    id integer NOT NULL,
    strategy_id integer,
    user_id integer,
    parameter_name character varying(255) NOT NULL,
    parameter_value jsonb NOT NULL,
    parameter_type character varying(50) NOT NULL,
    default_value jsonb,
    min_value numeric,
    max_value numeric,
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE strategy_parameters; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.strategy_parameters IS 'Configurable parameters for each pattern by user';


--
-- Name: pattern_parameters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pattern_parameters_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pattern_parameters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pattern_parameters_id_seq OWNED BY public.strategy_parameters.id;


--
-- Name: strategy_performance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_performance (
    id integer NOT NULL,
    strategy_id integer,
    user_id integer,
    symbol character varying(255),
    timeframe character varying(10),
    total_trades integer DEFAULT 0,
    winning_trades integer DEFAULT 0,
    losing_trades integer DEFAULT 0,
    win_rate numeric(6,4),
    avg_win numeric(18,8),
    avg_loss numeric(18,8),
    profit_factor numeric(8,4),
    total_pnl numeric(18,8) DEFAULT 0,
    max_consecutive_wins integer DEFAULT 0,
    max_consecutive_losses integer DEFAULT 0,
    avg_trade_duration_minutes integer,
    max_drawdown numeric(18,8),
    max_drawdown_percent numeric(6,4),
    sharpe_ratio numeric(8,4),
    sortino_ratio numeric(8,4),
    first_trade_at timestamp with time zone,
    last_trade_at timestamp with time zone,
    last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) DEFAULT 'ACTIVE'::character varying,
    CONSTRAINT pattern_performance_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'PAPER_TRADING'::character varying, 'DISABLED'::character varying])::text[])))
);


--
-- Name: TABLE strategy_performance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.strategy_performance IS 'Performance tracking for patterns by symbol and timeframe';


--
-- Name: pattern_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pattern_performance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pattern_performance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pattern_performance_id_seq OWNED BY public.strategy_performance.id;


--
-- Name: strategy_regime_performance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_regime_performance (
    id integer NOT NULL,
    strategy_id integer,
    user_id integer,
    regime character varying(50) NOT NULL,
    symbol character varying(255),
    total_trades integer DEFAULT 0,
    win_rate numeric(6,4),
    avg_profit numeric(18,8),
    avg_loss numeric(18,8),
    total_pnl numeric(18,8) DEFAULT 0,
    profit_factor numeric(8,4),
    max_drawdown numeric(6,4),
    regime_detection_accuracy numeric(6,4),
    false_signal_rate numeric(6,4),
    last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pattern_regime_performance_regime_check CHECK (((regime)::text = ANY ((ARRAY['BULL'::character varying, 'BEAR'::character varying, 'SIDEWAYS'::character varying, 'HIGH_VOLATILITY'::character varying, 'LOW_VOLATILITY'::character varying])::text[])))
);


--
-- Name: TABLE strategy_regime_performance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.strategy_regime_performance IS 'Pattern performance across different market regimes';


--
-- Name: pattern_regime_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pattern_regime_performance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pattern_regime_performance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pattern_regime_performance_id_seq OWNED BY public.strategy_regime_performance.id;


--
-- Name: strategy_training_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_training_results (
    id integer NOT NULL,
    strategy_name character varying(255) NOT NULL,
    symbol character varying(50) NOT NULL,
    training_parameters jsonb,
    success_rate double precision,
    sharpe_ratio double precision,
    max_drawdown double precision,
    total_trades integer,
    training_duration interval,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE strategy_training_results; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.strategy_training_results IS 'AI/ML training results and optimization data';


--
-- Name: pattern_training_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pattern_training_results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pattern_training_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pattern_training_results_id_seq OWNED BY public.strategy_training_results.id;


--
-- Name: strategies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategies (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    category character varying(100),
    implementation_class character varying(255),
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    version character varying(50) DEFAULT '1.0'::character varying,
    min_confidence numeric(4,3) DEFAULT 0.5,
    max_risk_per_trade numeric(4,3) DEFAULT 0.02
);


--
-- Name: TABLE strategies; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.strategies IS 'Pattern definitions and metadata';


--
-- Name: patterns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.patterns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: patterns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.patterns_id_seq OWNED BY public.strategies.id;


--
-- Name: performance_metrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.performance_metrics (
    id integer NOT NULL,
    user_id integer,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    total_return numeric(18,8),
    total_return_percent numeric(8,4),
    sharpe_ratio numeric(8,4),
    max_drawdown numeric(8,4),
    max_drawdown_percent numeric(8,4),
    win_rate numeric(8,4),
    profit_factor numeric(8,4),
    avg_win numeric(18,8),
    avg_loss numeric(18,8),
    largest_win numeric(18,8),
    largest_loss numeric(18,8),
    total_trades integer DEFAULT 0,
    winning_trades integer DEFAULT 0,
    losing_trades integer DEFAULT 0,
    avg_trade_duration_hours numeric(8,2),
    volatility numeric(8,4),
    alpha numeric(8,4),
    beta numeric(8,4),
    calculated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE performance_metrics; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.performance_metrics IS 'Calculated performance statistics by period';


--
-- Name: performance_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.performance_metrics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: performance_metrics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.performance_metrics_id_seq OWNED BY public.performance_metrics.id;


--
-- Name: policy_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policy_config (
    id integer NOT NULL,
    reward_weights text NOT NULL,
    risk_params text NOT NULL,
    last_updated timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: policy_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.policy_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: policy_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.policy_config_id_seq OWNED BY public.policy_config.id;


--
-- Name: portfolio_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolio_history (
    id integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    cash double precision NOT NULL,
    equity double precision NOT NULL,
    wallet_id character varying(255) DEFAULT 'unknown'::character varying NOT NULL
);


--
-- Name: portfolio_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.portfolio_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: portfolio_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.portfolio_history_id_seq OWNED BY public.portfolio_history.id;


--
-- Name: portfolio_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolio_snapshots (
    id integer NOT NULL,
    user_id integer,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    total_equity numeric(18,8) DEFAULT 0 NOT NULL,
    cash_balance numeric(18,8) DEFAULT 0 NOT NULL,
    unrealized_pnl numeric(18,8) DEFAULT 0,
    realized_pnl numeric(18,8) DEFAULT 0,
    total_pnl numeric(18,8) DEFAULT 0,
    position_count integer DEFAULT 0,
    market_value numeric(18,8) DEFAULT 0
);


--
-- Name: TABLE portfolio_snapshots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.portfolio_snapshots IS 'Point-in-time portfolio state snapshots';


--
-- Name: portfolio_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.portfolio_snapshots_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: portfolio_snapshots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.portfolio_snapshots_id_seq OWNED BY public.portfolio_snapshots.id;


--
-- Name: symbol_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.symbol_status (
    id integer NOT NULL,
    symbol character varying(50) NOT NULL,
    status character varying(32) NOT NULL,
    reason text,
    last_checked timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: symbol_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.symbol_status_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: symbol_status_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.symbol_status_id_seq OWNED BY public.symbol_status.id;


--
-- Name: ticker_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticker_data (
    id bigint NOT NULL,
    exchange character varying(50) NOT NULL,
    symbol character varying(20) NOT NULL,
    "timestamp" bigint NOT NULL,
    last_price numeric(20,8) NOT NULL,
    bid numeric(20,8),
    ask numeric(20,8),
    high_24h numeric(20,8),
    low_24h numeric(20,8),
    volume_24h numeric(20,8),
    quote_volume_24h numeric(20,8),
    change_24h numeric(20,8),
    change_pct_24h numeric(10,6),
    vwap_24h numeric(20,8),
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE ticker_data; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ticker_data IS '24h ticker statistics for market overview';


--
-- Name: ticker_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ticker_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ticker_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ticker_data_id_seq OWNED BY public.ticker_data.id;


--
-- Name: trade_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trade_data (
    id bigint NOT NULL,
    exchange character varying(50) NOT NULL,
    symbol character varying(20) NOT NULL,
    trade_id character varying(100),
    "timestamp" bigint NOT NULL,
    price numeric(20,8) NOT NULL,
    amount numeric(20,8) NOT NULL,
    cost numeric(20,8) NOT NULL,
    side character varying(10),
    taker_or_maker character varying(10),
    created_at timestamp with time zone DEFAULT now()
)
WITH (fillfactor='90');


--
-- Name: TABLE trade_data; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.trade_data IS 'Individual trade data for tick-level analysis';


--
-- Name: trade_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trade_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trade_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trade_data_id_seq OWNED BY public.trade_data.id;


--
-- Name: trades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trades (
    id integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    symbol character varying(20) NOT NULL,
    exchange character varying(50) NOT NULL,
    quantity double precision NOT NULL,
    direction character varying(4) NOT NULL,
    price double precision NOT NULL,
    fill_cost double precision NOT NULL,
    commission double precision NOT NULL,
    user_id integer,
    fees numeric(18,8) DEFAULT 0,
    order_id character varying(255),
    executed_at timestamp with time zone,
    pnl_percent numeric(8,4),
    strategy_id integer,
    strategy_name character varying(255),
    entry_signal text,
    exit_signal text
);


--
-- Name: TABLE trades; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.trades IS 'All executed trades with performance data';


--
-- Name: trades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trades_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trades_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trades_id_seq OWNED BY public.trades.id;


--
-- Name: trained_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trained_configurations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_name character varying(100) NOT NULL,
    exchange character varying(50) NOT NULL,
    pair character varying(20) NOT NULL,
    timeframe character varying(10) NOT NULL,
    regime character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'DISCOVERY'::character varying NOT NULL,
    is_active boolean DEFAULT false,
    parameters_json jsonb NOT NULL,
    gross_win_rate numeric(5,4),
    avg_win numeric(15,2),
    avg_loss numeric(15,2),
    net_profit numeric(15,2),
    sample_size integer,
    exchange_fees numeric(15,2),
    est_slippage numeric(15,2),
    actual_slippage numeric(15,2),
    sharpe_ratio numeric(8,4),
    calmar_ratio numeric(8,4),
    sortino_ratio numeric(8,4),
    p_value numeric(8,6),
    z_score numeric(8,4),
    monte_carlo_var numeric(15,2),
    stability_score numeric(5,4),
    drawdown_duration integer,
    trade_clustering numeric(5,4),
    rolling_30d_sharpe numeric(8,4),
    lifetime_sharpe_ratio numeric(8,4),
    fill_rate numeric(5,4),
    partial_fill_rate numeric(5,4),
    time_to_fill_ms integer,
    slippage_vs_mid_bps numeric(8,2),
    adverse_selection_score numeric(5,4),
    post_trade_drift_1m numeric(8,2),
    post_trade_drift_5m numeric(8,2),
    rejection_rate numeric(5,4),
    regime_classification jsonb,
    alternative_data_signals jsonb,
    adversarial_score numeric(5,4),
    trap_probability numeric(5,4),
    smart_money_alignment numeric(5,4),
    kelly_fraction numeric(5,4),
    correlation_adjusted_weight numeric(5,4),
    regime_adjusted_size numeric(5,4),
    max_position_size numeric(15,2),
    current_allocation numeric(15,2),
    var_95 numeric(15,2),
    cvar_95 numeric(15,2),
    avg_spread_bps numeric(8,2),
    book_depth_ratio numeric(8,4),
    book_imbalance numeric(5,4),
    tick_size_impact numeric(8,4),
    maker_rebate numeric(8,4),
    taker_fee numeric(8,4),
    level2_depth_score numeric(5,4),
    microstructure_noise numeric(8,4),
    months_since_discovery integer,
    performance_degradation numeric(8,4),
    degradation_velocity numeric(8,4),
    death_signals jsonb,
    death_signal_count integer DEFAULT 0,
    resurrection_score numeric(5,4),
    model_version character varying(20),
    discovery_date timestamp with time zone,
    engine_hash character varying(64),
    runtime_env character varying(50),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_activated_at timestamp with time zone,
    last_deactivated_at timestamp with time zone,
    CONSTRAINT valid_regime CHECK (((regime)::text = ANY ((ARRAY['bull'::character varying, 'bear'::character varying, 'sideways'::character varying, 'volatile'::character varying])::text[]))),
    CONSTRAINT valid_status CHECK (((status)::text = ANY ((ARRAY['DISCOVERY'::character varying, 'VALIDATION'::character varying, 'MATURE'::character varying, 'DECAY'::character varying, 'PAPER'::character varying])::text[]))),
    CONSTRAINT valid_timeframe CHECK (((timeframe)::text = ANY ((ARRAY['1m'::character varying, '5m'::character varying, '15m'::character varying, '1h'::character varying, '4h'::character varying, '1d'::character varying])::text[])))
);


--
-- Name: TABLE trained_configurations; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.trained_configurations IS 'Stores optimized strategy configurations with comprehensive performance and risk metrics';


--
-- Name: training_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_jobs (
    id integer NOT NULL,
    job_id text NOT NULL,
    strategy text NOT NULL,
    symbol text NOT NULL,
    exchange text NOT NULL,
    timeframe text NOT NULL,
    optimizer text NOT NULL,
    lookback_days integer DEFAULT 90,
    n_iterations integer,
    parameter_space jsonb,
    status text DEFAULT 'PENDING'::text NOT NULL,
    progress_pct numeric DEFAULT 0,
    current_iteration integer DEFAULT 0,
    total_iterations integer,
    created_at timestamp without time zone DEFAULT now(),
    started_at timestamp without time zone,
    completed_at timestamp without time zone,
    duration_seconds integer,
    best_config_id text,
    best_score numeric,
    best_parameters jsonb,
    best_metrics jsonb,
    error_message text,
    error_trace text,
    created_by text,
    metadata jsonb,
    CONSTRAINT valid_optimizer CHECK ((optimizer = ANY (ARRAY['grid'::text, 'random'::text, 'bayesian'::text]))),
    CONSTRAINT valid_status CHECK ((status = ANY (ARRAY['PENDING'::text, 'RUNNING'::text, 'COMPLETED'::text, 'FAILED'::text, 'CANCELLED'::text])))
);


--
-- Name: TABLE training_jobs; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.training_jobs IS 'Tracks training job execution status and results';


--
-- Name: COLUMN training_jobs.job_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_jobs.job_id IS 'Unique job identifier (UUID)';


--
-- Name: COLUMN training_jobs.optimizer; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_jobs.optimizer IS 'Optimization algorithm: grid, random, bayesian';


--
-- Name: COLUMN training_jobs.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_jobs.status IS 'Job status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED';


--
-- Name: COLUMN training_jobs.progress_pct; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_jobs.progress_pct IS 'Job completion percentage (0-100)';


--
-- Name: COLUMN training_jobs.best_config_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_jobs.best_config_id IS 'Foreign key to trained_configurations.config_id';


--
-- Name: training_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.training_jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: training_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.training_jobs_id_seq OWNED BY public.training_jobs.id;


--
-- Name: training_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_progress (
    id bigint NOT NULL,
    job_id character varying(255) NOT NULL,
    percentage double precision DEFAULT 0.0 NOT NULL,
    current_step character varying(100) NOT NULL,
    step_number integer DEFAULT 1 NOT NULL,
    total_steps integer DEFAULT 4 NOT NULL,
    step_percentage double precision DEFAULT 0.0 NOT NULL,
    step_details jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    estimated_completion timestamp with time zone,
    current_iteration integer,
    total_iterations integer,
    best_score double precision,
    current_score double precision,
    best_params jsonb,
    is_complete boolean DEFAULT false NOT NULL,
    error_message text
);


--
-- Name: training_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.training_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: training_progress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.training_progress_id_seq OWNED BY public.training_progress.id;


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    id integer NOT NULL,
    user_id integer,
    preference_key character varying(255) NOT NULL,
    preference_value jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE user_preferences; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_preferences IS 'User-specific preferences and dashboard customization';


--
-- Name: COLUMN user_preferences.preference_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_preferences.preference_value IS 'JSON object containing preference data';


--
-- Name: user_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_preferences_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_preferences_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_preferences_id_seq OWNED BY public.user_preferences.id;


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    id integer NOT NULL,
    user_id integer,
    session_token character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_accessed timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    user_agent text
);


--
-- Name: TABLE user_sessions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_sessions IS 'Active user sessions for authentication tracking';


--
-- Name: COLUMN user_sessions.session_token; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_sessions.session_token IS 'JWT or secure random token for session identification';


--
-- Name: user_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_sessions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_sessions_id_seq OWNED BY public.user_sessions.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255),
    password_hash character varying(255) NOT NULL,
    display_name character varying(255),
    is_active boolean DEFAULT true,
    is_admin boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS 'User accounts for multi-tenant trading platform';


--
-- Name: COLUMN users.password_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.password_hash IS 'BCrypt hashed password';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: volume_by_timeframe; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.volume_by_timeframe AS
 SELECT symbol,
    timeframe,
    exchange,
    avg(volume) AS avg_volume,
    sum(volume) AS total_volume,
    count(*) AS candle_count,
    min(to_timestamp((("timestamp" / 1000))::double precision)) AS start_date,
    max(to_timestamp((("timestamp" / 1000))::double precision)) AS end_date
   FROM public.market_data
  GROUP BY symbol, timeframe, exchange
  ORDER BY symbol, timeframe, (sum(volume)) DESC;


--
-- Name: active_trades id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_trades ALTER COLUMN id SET DEFAULT nextval('public.active_trades_id_seq'::regclass);


--
-- Name: backtest_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backtest_results ALTER COLUMN id SET DEFAULT nextval('public.backtest_results_id_seq'::regclass);


--
-- Name: collection_runs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_runs ALTER COLUMN id SET DEFAULT nextval('public.collection_runs_id_seq'::regclass);


--
-- Name: equity_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equity_history ALTER COLUMN id SET DEFAULT nextval('public.equity_history_id_seq'::regclass);


--
-- Name: holdings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings ALTER COLUMN id SET DEFAULT nextval('public.holdings_id_seq'::regclass);


--
-- Name: market_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_data ALTER COLUMN id SET DEFAULT nextval('public.market_data_enhanced_id_seq'::regclass);


--
-- Name: market_state id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_state ALTER COLUMN id SET DEFAULT nextval('public.market_state_id_seq'::regclass);


--
-- Name: order_book_snapshots id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_book_snapshots ALTER COLUMN id SET DEFAULT nextval('public.order_book_snapshots_id_seq'::regclass);


--
-- Name: performance_metrics id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance_metrics ALTER COLUMN id SET DEFAULT nextval('public.performance_metrics_id_seq'::regclass);


--
-- Name: policy_config id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_config ALTER COLUMN id SET DEFAULT nextval('public.policy_config_id_seq'::regclass);


--
-- Name: portfolio_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_history ALTER COLUMN id SET DEFAULT nextval('public.portfolio_history_id_seq'::regclass);


--
-- Name: portfolio_snapshots id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_snapshots ALTER COLUMN id SET DEFAULT nextval('public.portfolio_snapshots_id_seq'::regclass);


--
-- Name: strategies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategies ALTER COLUMN id SET DEFAULT nextval('public.patterns_id_seq'::regclass);


--
-- Name: strategy_exchange_performance id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_exchange_performance ALTER COLUMN id SET DEFAULT nextval('public.pattern_exchange_performance_id_seq'::regclass);


--
-- Name: strategy_parameters id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_parameters ALTER COLUMN id SET DEFAULT nextval('public.pattern_parameters_id_seq'::regclass);


--
-- Name: strategy_performance id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_performance ALTER COLUMN id SET DEFAULT nextval('public.pattern_performance_id_seq'::regclass);


--
-- Name: strategy_regime_performance id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_regime_performance ALTER COLUMN id SET DEFAULT nextval('public.pattern_regime_performance_id_seq'::regclass);


--
-- Name: strategy_training_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_training_results ALTER COLUMN id SET DEFAULT nextval('public.pattern_training_results_id_seq'::regclass);


--
-- Name: symbol_status id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.symbol_status ALTER COLUMN id SET DEFAULT nextval('public.symbol_status_id_seq'::regclass);


--
-- Name: ticker_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticker_data ALTER COLUMN id SET DEFAULT nextval('public.ticker_data_id_seq'::regclass);


--
-- Name: trade_data id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_data ALTER COLUMN id SET DEFAULT nextval('public.trade_data_id_seq'::regclass);


--
-- Name: trades id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trades ALTER COLUMN id SET DEFAULT nextval('public.trades_id_seq'::regclass);


--
-- Name: training_jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_jobs ALTER COLUMN id SET DEFAULT nextval('public.training_jobs_id_seq'::regclass);


--
-- Name: training_progress id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_progress ALTER COLUMN id SET DEFAULT nextval('public.training_progress_id_seq'::regclass);


--
-- Name: user_preferences id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences ALTER COLUMN id SET DEFAULT nextval('public.user_preferences_id_seq'::regclass);


--
-- Name: user_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions ALTER COLUMN id SET DEFAULT nextval('public.user_sessions_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: active_trades active_trades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_trades
    ADD CONSTRAINT active_trades_pkey PRIMARY KEY (id);


--
-- Name: backtest_results backtest_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backtest_results
    ADD CONSTRAINT backtest_results_pkey PRIMARY KEY (id);


--
-- Name: collection_runs collection_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_runs
    ADD CONSTRAINT collection_runs_pkey PRIMARY KEY (id);


--
-- Name: equity_history equity_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equity_history
    ADD CONSTRAINT equity_history_pkey PRIMARY KEY (id);


--
-- Name: equity_history equity_history_user_id_timestamp_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equity_history
    ADD CONSTRAINT equity_history_user_id_timestamp_key UNIQUE (user_id, "timestamp");


--
-- Name: holdings holdings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT holdings_pkey PRIMARY KEY (id);


--
-- Name: holdings holdings_user_id_symbol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT holdings_user_id_symbol_key UNIQUE (user_id, symbol);


--
-- Name: market_data market_data_enhanced_exchange_symbol_timeframe_timestamp_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_data
    ADD CONSTRAINT market_data_enhanced_exchange_symbol_timeframe_timestamp_key UNIQUE (exchange, symbol, timeframe, "timestamp");


--
-- Name: market_data market_data_enhanced_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_data
    ADD CONSTRAINT market_data_enhanced_pkey PRIMARY KEY (id);


--
-- Name: market_state market_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_state
    ADD CONSTRAINT market_state_pkey PRIMARY KEY (id);


--
-- Name: order_book_snapshots order_book_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_book_snapshots
    ADD CONSTRAINT order_book_snapshots_pkey PRIMARY KEY (id);


--
-- Name: performance_metrics performance_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance_metrics
    ADD CONSTRAINT performance_metrics_pkey PRIMARY KEY (id);


--
-- Name: policy_config policy_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_config
    ADD CONSTRAINT policy_config_pkey PRIMARY KEY (id);


--
-- Name: portfolio_history portfolio_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_history
    ADD CONSTRAINT portfolio_history_pkey PRIMARY KEY (id);


--
-- Name: portfolio_snapshots portfolio_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_snapshots
    ADD CONSTRAINT portfolio_snapshots_pkey PRIMARY KEY (id);


--
-- Name: strategy_exchange_performance strategy_exchange_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_exchange_performance
    ADD CONSTRAINT strategy_exchange_performance_pkey PRIMARY KEY (id);


--
-- Name: strategy_exchange_performance strategy_exchange_performance_strategy_id_user_id_exchange_sy_k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_exchange_performance
    ADD CONSTRAINT strategy_exchange_performance_strategy_id_user_id_exchange_sy_k UNIQUE (strategy_id, user_id, exchange, symbol);


--
-- Name: strategy_parameters strategy_parameters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_parameters
    ADD CONSTRAINT strategy_parameters_pkey PRIMARY KEY (id);


--
-- Name: strategy_parameters strategy_parameters_strategy_id_user_id_parameter_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_parameters
    ADD CONSTRAINT strategy_parameters_strategy_id_user_id_parameter_name_key UNIQUE (strategy_id, user_id, parameter_name);


--
-- Name: strategy_performance strategy_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_performance
    ADD CONSTRAINT strategy_performance_pkey PRIMARY KEY (id);


--
-- Name: strategy_performance strategy_performance_strategy_id_user_id_symbol_timeframe_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_performance
    ADD CONSTRAINT strategy_performance_strategy_id_user_id_symbol_timeframe_key UNIQUE (strategy_id, user_id, symbol, timeframe);


--
-- Name: strategy_regime_performance strategy_regime_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_regime_performance
    ADD CONSTRAINT strategy_regime_performance_pkey PRIMARY KEY (id);


--
-- Name: strategy_regime_performance strategy_regime_performance_strategy_id_user_id_regime_symbol_k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_regime_performance
    ADD CONSTRAINT strategy_regime_performance_strategy_id_user_id_regime_symbol_k UNIQUE (strategy_id, user_id, regime, symbol);


--
-- Name: strategy_training_results strategy_training_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_training_results
    ADD CONSTRAINT strategy_training_results_pkey PRIMARY KEY (id);


--
-- Name: strategies strategys_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategies
    ADD CONSTRAINT strategys_name_key UNIQUE (name);


--
-- Name: strategies strategys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategies
    ADD CONSTRAINT strategys_pkey PRIMARY KEY (id);


--
-- Name: symbol_status symbol_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.symbol_status
    ADD CONSTRAINT symbol_status_pkey PRIMARY KEY (id);


--
-- Name: symbol_status symbol_status_symbol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.symbol_status
    ADD CONSTRAINT symbol_status_symbol_key UNIQUE (symbol);


--
-- Name: ticker_data ticker_data_exchange_symbol_timestamp_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticker_data
    ADD CONSTRAINT ticker_data_exchange_symbol_timestamp_key UNIQUE (exchange, symbol, "timestamp");


--
-- Name: ticker_data ticker_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticker_data
    ADD CONSTRAINT ticker_data_pkey PRIMARY KEY (id);


--
-- Name: trade_data trade_data_exchange_symbol_trade_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_data
    ADD CONSTRAINT trade_data_exchange_symbol_trade_id_key UNIQUE (exchange, symbol, trade_id);


--
-- Name: trade_data trade_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_data
    ADD CONSTRAINT trade_data_pkey PRIMARY KEY (id);


--
-- Name: trades trades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trades
    ADD CONSTRAINT trades_pkey PRIMARY KEY (id);


--
-- Name: trained_configurations trained_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trained_configurations
    ADD CONSTRAINT trained_configurations_pkey PRIMARY KEY (id);


--
-- Name: training_jobs training_jobs_job_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_jobs
    ADD CONSTRAINT training_jobs_job_id_key UNIQUE (job_id);


--
-- Name: training_jobs training_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_jobs
    ADD CONSTRAINT training_jobs_pkey PRIMARY KEY (id);


--
-- Name: training_progress training_progress_job_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_progress
    ADD CONSTRAINT training_progress_job_id_key UNIQUE (job_id);


--
-- Name: training_progress training_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_progress
    ADD CONSTRAINT training_progress_pkey PRIMARY KEY (id);


--
-- Name: trained_configurations unique_configuration; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trained_configurations
    ADD CONSTRAINT unique_configuration UNIQUE (strategy_name, exchange, pair, timeframe, regime);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);


--
-- Name: user_preferences user_preferences_user_id_preference_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_preference_key_key UNIQUE (user_id, preference_key);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


--
-- Name: user_sessions user_sessions_session_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_session_token_key UNIQUE (session_token);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_active_trades_symbol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_active_trades_symbol ON public.active_trades USING btree (symbol);


--
-- Name: idx_active_trades_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_active_trades_user_id ON public.active_trades USING btree (user_id);


--
-- Name: idx_current_embeddings_symbol_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_current_embeddings_symbol_timestamp ON public.current_embeddings USING btree (symbol, "timestamp" DESC);


--
-- Name: idx_equity_history_user_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equity_history_user_timestamp ON public.equity_history USING btree (user_id, "timestamp" DESC);


--
-- Name: idx_holdings_symbol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_holdings_symbol ON public.holdings USING btree (symbol);


--
-- Name: idx_holdings_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_holdings_user_id ON public.holdings USING btree (user_id);


--
-- Name: idx_market_data_enhanced_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_market_data_enhanced_lookup ON public.market_data USING btree (exchange, symbol, timeframe, "timestamp" DESC);


--
-- Name: idx_market_data_enhanced_symbol_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_market_data_enhanced_symbol_time ON public.market_data USING btree (symbol, timeframe, "timestamp" DESC);


--
-- Name: idx_market_data_enhanced_timeframe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_market_data_enhanced_timeframe ON public.market_data USING btree (timeframe, "timestamp" DESC);


--
-- Name: idx_order_book_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_book_lookup ON public.order_book_snapshots USING btree (exchange, symbol, "timestamp" DESC);


--
-- Name: idx_order_book_spread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_book_spread ON public.order_book_snapshots USING btree (symbol, spread_pct, "timestamp" DESC);


--
-- Name: idx_performance_metrics_user_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_performance_metrics_user_period ON public.performance_metrics USING btree (user_id, period_start, period_end);


--
-- Name: idx_portfolio_snapshots_user_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_portfolio_snapshots_user_timestamp ON public.portfolio_snapshots USING btree (user_id, "timestamp" DESC);


--
-- Name: idx_strategy_exchange_performance_exchange; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_exchange_performance_exchange ON public.strategy_exchange_performance USING btree (exchange);


--
-- Name: idx_strategy_exchange_performance_strategy_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_exchange_performance_strategy_user ON public.strategy_exchange_performance USING btree (strategy_id, user_id);


--
-- Name: idx_strategy_parameters_strategy_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_parameters_strategy_user ON public.strategy_parameters USING btree (strategy_id, user_id);


--
-- Name: idx_strategy_performance_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_performance_status ON public.strategy_performance USING btree (status);


--
-- Name: idx_strategy_performance_strategy_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_performance_strategy_user ON public.strategy_performance USING btree (strategy_id, user_id);


--
-- Name: idx_strategy_performance_symbol_timeframe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_performance_symbol_timeframe ON public.strategy_performance USING btree (symbol, timeframe);


--
-- Name: idx_strategy_regime_performance_regime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_regime_performance_regime ON public.strategy_regime_performance USING btree (regime);


--
-- Name: idx_strategy_regime_performance_strategy_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_regime_performance_strategy_user ON public.strategy_regime_performance USING btree (strategy_id, user_id);


--
-- Name: idx_strategys_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategys_active ON public.strategies USING btree (is_active);


--
-- Name: idx_strategys_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategys_name ON public.strategies USING btree (name);


--
-- Name: idx_ticker_data_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticker_data_lookup ON public.ticker_data USING btree (exchange, symbol, "timestamp" DESC);


--
-- Name: idx_ticker_data_volume; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticker_data_volume ON public.ticker_data USING btree (symbol, volume_24h DESC, "timestamp" DESC);


--
-- Name: idx_trade_data_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_data_lookup ON public.trade_data USING btree (exchange, symbol, "timestamp" DESC);


--
-- Name: idx_trade_data_side_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_data_side_time ON public.trade_data USING btree (side, "timestamp" DESC);


--
-- Name: idx_trade_data_symbol_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_data_symbol_time ON public.trade_data USING btree (symbol, "timestamp" DESC);


--
-- Name: idx_trades_executed_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trades_executed_at ON public.trades USING btree (executed_at DESC);


--
-- Name: idx_trades_symbol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trades_symbol ON public.trades USING btree (symbol);


--
-- Name: idx_trades_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trades_user_id ON public.trades USING btree (user_id);


--
-- Name: idx_trained_configs_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_active ON public.trained_configurations USING btree (is_active) WHERE (is_active = true);


--
-- Name: idx_trained_configs_context; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_context ON public.trained_configurations USING btree (exchange, pair, timeframe);


--
-- Name: idx_trained_configs_death_signals; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_death_signals ON public.trained_configurations USING gin (death_signals);


--
-- Name: idx_trained_configs_exchange; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_exchange ON public.trained_configurations USING btree (exchange);


--
-- Name: idx_trained_configs_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_lifecycle ON public.trained_configurations USING btree (status, months_since_discovery);


--
-- Name: idx_trained_configs_pair; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_pair ON public.trained_configurations USING btree (pair);


--
-- Name: idx_trained_configs_parameters; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_parameters ON public.trained_configurations USING gin (parameters_json);


--
-- Name: idx_trained_configs_performance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_performance ON public.trained_configurations USING btree (net_profit DESC, sharpe_ratio DESC);


--
-- Name: idx_trained_configs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_status ON public.trained_configurations USING btree (status);


--
-- Name: idx_trained_configs_strategy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trained_configs_strategy ON public.trained_configurations USING btree (strategy_name);


--
-- Name: idx_training_jobs_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_jobs_active ON public.training_jobs USING btree (status, created_at DESC) WHERE (status = ANY (ARRAY['PENDING'::text, 'RUNNING'::text]));


--
-- Name: idx_training_jobs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_jobs_created_at ON public.training_jobs USING btree (created_at DESC);


--
-- Name: idx_training_jobs_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_jobs_job_id ON public.training_jobs USING btree (job_id);


--
-- Name: idx_training_jobs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_jobs_status ON public.training_jobs USING btree (status);


--
-- Name: idx_training_jobs_strategy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_jobs_strategy ON public.training_jobs USING btree (strategy);


--
-- Name: idx_training_jobs_symbol_exchange; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_jobs_symbol_exchange ON public.training_jobs USING btree (symbol, exchange);


--
-- Name: idx_training_progress_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_progress_job_id ON public.training_progress USING btree (job_id);


--
-- Name: idx_training_progress_job_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_training_progress_job_updated ON public.training_progress USING btree (job_id, updated_at DESC);


--
-- Name: idx_user_preferences_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_preferences_user_id ON public.user_preferences USING btree (user_id);


--
-- Name: idx_user_sessions_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_sessions_expires ON public.user_sessions USING btree (expires_at);


--
-- Name: idx_user_sessions_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_sessions_token ON public.user_sessions USING btree (session_token);


--
-- Name: idx_user_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_sessions_user_id ON public.user_sessions USING btree (user_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_username ON public.users USING btree (username);


--
-- Name: training_progress training_progress_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER training_progress_updated_at BEFORE UPDATE ON public.training_progress FOR EACH ROW EXECUTE FUNCTION public.update_training_progress_timestamp();


--
-- Name: trained_configurations trigger_trained_configurations_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_trained_configurations_updated_at BEFORE UPDATE ON public.trained_configurations FOR EACH ROW EXECUTE FUNCTION public.update_trained_configurations_updated_at();


--
-- Name: active_trades active_trades_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_trades
    ADD CONSTRAINT active_trades_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: equity_history equity_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equity_history
    ADD CONSTRAINT equity_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: training_progress fk_training_job; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_progress
    ADD CONSTRAINT fk_training_job FOREIGN KEY (job_id) REFERENCES public.training_jobs(job_id) ON DELETE CASCADE;


--
-- Name: holdings holdings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT holdings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: strategy_exchange_performance pattern_exchange_performance_pattern_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_exchange_performance
    ADD CONSTRAINT pattern_exchange_performance_pattern_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id) ON DELETE CASCADE;


--
-- Name: strategy_exchange_performance pattern_exchange_performance_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_exchange_performance
    ADD CONSTRAINT pattern_exchange_performance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: strategy_regime_performance pattern_regime_performance_pattern_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_regime_performance
    ADD CONSTRAINT pattern_regime_performance_pattern_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id) ON DELETE CASCADE;


--
-- Name: strategy_regime_performance pattern_regime_performance_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_regime_performance
    ADD CONSTRAINT pattern_regime_performance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: strategies patterns_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategies
    ADD CONSTRAINT patterns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: performance_metrics performance_metrics_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance_metrics
    ADD CONSTRAINT performance_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: portfolio_snapshots portfolio_snapshots_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolio_snapshots
    ADD CONSTRAINT portfolio_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: strategy_parameters strategy_parameters_strategy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_parameters
    ADD CONSTRAINT strategy_parameters_strategy_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id) ON DELETE CASCADE;


--
-- Name: strategy_performance strategy_performance_strategy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_performance
    ADD CONSTRAINT strategy_performance_strategy_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id) ON DELETE CASCADE;


--
-- Name: trades trades_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trades
    ADD CONSTRAINT trades_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_sessions user_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict C6tHVQKeckSFsJ7JVQA8AIYSlw4roa48ZGzaY5JRCgtUCJQBrWGxx5psObkHEL7

